### ISSUE TITLE
Riotphobia not starting

### ISSUE THREAD

**Issue by stdbasti** [Riotphobia/Oldseason#1]
[log.txt](https://github.com/Riotphobia/Oldseason/files/10951190/log.txt)
log is attached, intellij is throwing 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Range [7, -1) out of bounds for length 10
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at com.hawolt.oldseason.Main.rewrite(Main.java:139)
	at com.hawolt.oldseason.Main.main(Main.java:61)

**Comment by hawolt** [comment]
Can you attach these two files
* `C:\Riot Games\League of Legends\system.yaml`
* `C:\Riot Games\League of Legends\system.yaml.backup`

**Comment by stdbasti** [comment]
deleted both once to reset it, works now. dunno what was the error but somehow the system.yaml was broken.
league worked without oldseason before so i dunno what the problem was
